import { PRODUCT_PHOTOSHOOT_FORMAT, type CreateFormatId } from "./createFormats";

export type CreateFormatGuide = {
  format: CreateFormatId;
  label: string;
  promise: string;
  why: string;
  bestForExample: string;
  skipWhen: string;
  bestFor: readonly ("Cold" | "Retargeting" | "Conversion" | "Organic" | "Asset" | "Audio")[];
  output: string;
  needs: readonly ("reviews" | "products" | "audio" | "video" | "none")[];
  cost: "free-ish" | "audio" | "image" | "video";
  accent: string;
};

export const CREATE_FORMAT_GUIDES = {
  meme: {
    format: "meme",
    label: "Meme",
    promise: "A brand joke in a meme format people already understand.",
    why: "Memes work when the joke names the buyer's daily frustration faster than polished ad copy can. They are best as cheap cold or organic creative tests.",
    bestForExample: "Playful brands testing many cold hooks cheaply.",
    skipWhen: "Humor would create compliance risk or make the brand feel less trustworthy.",
    bestFor: ["Cold", "Organic"],
    output: "12 drafts",
    needs: ["none"],
    cost: "free-ish",
    accent: "#111827",
  },
  "were-sorry": {
    format: "were-sorry",
    label: "We're Sorry",
    promise: "A fake apology letter that reveals the product as the fix.",
    why: "The apology frame gives the brand permission to be funny while still teaching the pain and the fix. It is a fast way to make cold audiences stop scrolling.",
    bestForExample: "Brands solving an annoying problem people already complain about.",
    skipWhen: "An apology tone would feel manipulative, too serious, or off-brand.",
    bestFor: ["Cold", "Organic"],
    output: "8 posts",
    needs: ["none"],
    cost: "free-ish",
    accent: "#F97316",
  },
  "video-meme": {
    format: "video-meme",
    label: "Video Meme",
    promise: "A trending reaction clip with brand-specific captions.",
    why: "The familiar video does the stopping, and Wiggly writes the brand-specific caption that gives the moment a selling angle.",
    bestForExample: "Social-first brands that need fast TikTok or Reels-style concepts.",
    skipWhen: "The brand should not look trend-chasing or the product needs careful explanation.",
    bestFor: ["Cold", "Organic"],
    output: "3-8 clips",
    needs: ["video"],
    cost: "free-ish",
    accent: "#2563EB",
  },
  jingle: {
    format: "jingle",
    label: "Brand Jingle",
    promise: "A short original song about the brand.",
    why: "Music makes a simple offer easier to remember. Use it when recall, shareability, and a stronger creative hook matter more than a direct proof claim.",
    bestForExample: "Brands with a sticky name, tagline, or product promise.",
    skipWhen: "The buyer expects a formal enterprise tone or the offer needs strict proof.",
    bestFor: ["Cold", "Organic", "Audio"],
    output: "1 song",
    needs: ["audio"],
    cost: "audio",
    accent: "#7C3AED",
  },
  "text-message": {
    format: "text-message",
    label: "iMessage",
    promise: "A fake text-message conversation about the product.",
    why: "Text-message ads work because they look like a private conversation, not an ad. They are useful once buyers already recognize the problem.",
    bestForExample: "Products with a clear problem-solution moment people would recommend to a friend.",
    skipWhen: "The product needs a visual demo before the buyer understands it.",
    bestFor: ["Retargeting", "Conversion"],
    output: "6 texts",
    needs: ["none"],
    cost: "free-ish",
    accent: "#0EA5E9",
  },
  brainrot: {
    format: "brainrot",
    label: "Minecraft Brainrot",
    promise: "Two characters argue about the offer over Minecraft gameplay.",
    why: "The gameplay holds attention while the characters turn the offer into a short argument. It is a cheap audio format for cold and organic testing.",
    bestForExample: "Brands that can be funny and want loud scroll-stopping content.",
    skipWhen: "A premium or conservative brand would be hurt by absurd humor.",
    bestFor: ["Cold", "Organic", "Audio"],
    output: "3 scripts",
    needs: ["audio", "video"],
    cost: "audio",
    accent: "#22C55E",
  },
  reviews: {
    format: "reviews",
    label: "Reviews",
    promise: "An ad built around a real customer review.",
    why: "Proof lowers risk. This format is strongest when buyers already care and need one last credible reason to trust the brand.",
    bestForExample: "Brands with strong reviews, ratings, testimonials, or customer quotes.",
    skipWhen: "The site has no usable real reviews or proof Wiggly can verify.",
    bestFor: ["Retargeting", "Conversion"],
    output: "8 proof ads",
    needs: ["reviews"],
    cost: "free-ish",
    accent: "#E11D48",
  },
  "motion-story": {
    format: "motion-story",
    label: "Motion Story",
    promise: "A premium 20-second product story video.",
    why: "This is the polished hero asset for a best seller. It gives the product, proof, and CTA a launch-video feel without AI video generation.",
    bestForExample: "Best sellers, launches, retargeting, and brands that want the product to feel expensive.",
    skipWhen: "There is no product image or real review strong enough to carry the story.",
    bestFor: ["Retargeting", "Conversion"],
    output: "4 stories",
    needs: ["products", "reviews", "audio"],
    cost: "image",
    accent: "#A855F7",
  },
  "three-d-breakdown": {
    format: "three-d-breakdown",
    label: "3D Breakdown",
    promise: "A narrated 3D explainer that opens on the consequence.",
    why: "This is the cinematic education lane: Wiggly writes two consequence-first story directions, then you explicitly choose when to spend on 3D images, animation, and MP4 export.",
    bestForExample: "Products or offers with a clear mechanism, surprising proof, or dramatic before/after.",
    skipWhen: "The site has no concrete scraped proof, product detail, guarantee, result, or claim to ground the revelation.",
    bestFor: ["Cold", "Organic", "Audio"],
    output: "2 scripts",
    needs: ["audio", "video"],
    cost: "video",
    accent: "#0F766E",
  },
  visualizer: {
    format: "visualizer",
    label: "Visualizer",
    promise: "A voice-led explainer with captions and waveform motion.",
    why: "When the offer needs clarity, voice plus captions can explain the pain, fix, and CTA without asking the user to read a dense ad.",
    bestForExample: "SaaS, tools, supplements, or offers that need a short explanation.",
    skipWhen: "The product is an impulse buy where explanation slows the sale down.",
    bestFor: ["Cold", "Retargeting", "Audio"],
    output: "1 audio ad",
    needs: ["audio"],
    cost: "audio",
    accent: "#38BDF8",
  },
  [PRODUCT_PHOTOSHOOT_FORMAT]: {
    format: PRODUCT_PHOTOSHOOT_FORMAT,
    label: "Product Photoshoot",
    promise: "Six polished product photos from one real product image.",
    why: "This is an asset workflow, not an ad. Use it when the brand needs better product visuals before turning those assets into paid creative.",
    bestForExample: "Stores with weak product imagery that need social, PDP, or email assets.",
    skipWhen: "The brand already has strong professional photography for the product.",
    bestFor: ["Asset", "Organic"],
    output: "6 stills",
    needs: ["products"],
    cost: "image",
    accent: "#FACC15",
  },
} satisfies Record<CreateFormatId, CreateFormatGuide>;

export const CREATE_FORMAT_GUIDE_ORDER = [
  "meme",
  "were-sorry",
  "video-meme",
  "jingle",
  "text-message",
  "brainrot",
  "reviews",
  "motion-story",
  "three-d-breakdown",
  PRODUCT_PHOTOSHOOT_FORMAT,
  "visualizer",
] as const satisfies readonly CreateFormatId[];
