import type { StaticPackageAdScene, StaticTextLayer } from "../../scene/types";

const textLayer = (
  id: string,
  text: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fontSize: number,
  color = "#111111",
  fontWeight = 500,
): StaticTextLayer => ({
  id,
  type: "text",
  name: text,
  text,
  x,
  y,
  width,
  height,
  rotation: 0,
  visible: true,
  locked: false,
  opacity: 1,
  zIndex: 2,
  binding: "campaign",
  semanticRole: id,
  color,
  fontFamily: "Geist Variable, Inter, sans-serif",
  fontSize,
  fontWeight,
  lineHeight: 1,
  textAlign: "left",
});

export function createStaticPackageFixture(sourceName = "Codex integrations reference"): StaticPackageAdScene {
  return {
    version: 1,
    format: "static-package",
    brand: {
      name: "Codex",
      url: "https://openai.com/codex/",
      host: "openai.com",
      title: "Codex",
      description: sourceName,
      faviconUrl: null,
      logoUrl: null,
      ogImageUrl: null,
      screenshotUrl: null,
      colors: ["#111111", "#B5B5B5", "#FFFFFF"],
      fonts: { feel: "sans" },
      vibeTags: ["minimal", "editorial"],
      receipts: {
        specificClaims: [],
        buyerMoments: [],
        exactSiteLanguage: ["Work with Codex"],
        namedProof: [],
      },
    },
    creative: {
      angleId: "integration-relationship",
      headline: "Codex works with the tools your team already uses",
      subheadline: "One active partner inside a familiar tool collection.",
      ctaText: "Work with Codex",
      headlineType: "contrast",
      selectedPain: "Work is split across tools.",
      selectedProof: "Codex integrates with team tools.",
    },
    style: {
      backgroundColor: "#FFFFFF",
      textColor: "#111111",
      accentColor: "#B5B5B5",
      fontFeel: "sans",
    },
    audio: { status: "none", transcript: "", captions: [] },
    layout: {
      preset: "static-package",
      canvas: { width: 1080, height: 1080, backgroundColor: "#FFFFFF" },
      layers: [
        textLayer("supporting-tools", "GitHub\nSheets\nAsana\nDocs", 570, -35, 430, 520, 104, "#AFAFAF", 420),
        textLayer("active-brand", "Codex", 98, 475, 395, 125, 112, "#050505", 520),
        textLayer("relationship-symbol", "🤝", 492, 493, 118, 100, 82, "#111111", 500),
        { ...textLayer("active-tool", "Slack", 640, 475, 350, 125, 112, "#050505", 520), name: "Active tool", semanticRole: "list:integration_tools:active" },
        textLayer("remaining-tools", "Gmail\nSlides", 635, 605, 340, 250, 104, "#C7C7C7", 420),
        textLayer("footer-mark", "◉", 110, 878, 100, 90, 72, "#050505", 600),
        textLayer("footer-cta", "Work with Codex", 222, 879, 590, 90, 56, "#050505", 500),
      ],
    },
    metadata: {
      candidateIndex: 0,
      generationBatchId: "maker-fixture",
      researchRunId: "maker-fixture",
      brandSnapshotId: "maker-fixture",
      model: "saved-analysis-fixture",
      provider: "deterministic",
      generatedAt: 0,
    },
  };
}
