import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import {
  CREATIVE_PACK_CONCURRENCY,
  CREATIVE_PACK_EXCLUDED_FORMATS,
  CREATIVE_PACK_FORMATS,
  CREATIVE_PACK_FORMAT_TIMEOUT_MS,
  isCreativePackFormat,
} from "../features/create/creativePack";

const createClientSource = readFileSync("app/create/CreateResearchClient.tsx", "utf8");
const leftColumnSource = readFileSync("app/create/CreateLeftColumn.tsx", "utf8");
const overviewSource = readFileSync("app/create/CreateCreativePackOverview.tsx", "utf8");

assert.deepEqual(
  CREATIVE_PACK_FORMATS.map((item) => item.format),
  ["reviews", "video-meme", "meme", "text-message", "were-sorry", "visualizer"],
  "Creative Pack MVP must include only the cheap default formats in the planned order.",
);
assert.deepEqual(
  CREATIVE_PACK_EXCLUDED_FORMATS,
  ["jingle", "brainrot"],
  "Creative Pack MVP must exclude paid generated-audio formats.",
);
assert.equal(CREATIVE_PACK_CONCURRENCY, 3, "Creative Pack must run exactly three format generations at once.");
assert.equal(CREATIVE_PACK_FORMAT_TIMEOUT_MS, 20_000, "Creative Pack must time out each format after 20 seconds.");

for (const format of CREATIVE_PACK_FORMATS.map((item) => item.format)) {
  assert.equal(isCreativePackFormat(format), true, `${format} should be recognized as a Creative Pack format.`);
}
for (const expensiveFormat of CREATIVE_PACK_EXCLUDED_FORMATS) {
  assert.equal(isCreativePackFormat(expensiveFormat), false, `${expensiveFormat} must not be generated by Creative Pack.`);
}

assert.ok(
  leftColumnSource.includes("Generate creative pack") &&
    leftColumnSource.includes("data-generate-creative-pack") &&
    leftColumnSource.includes("data-cancel-creative-pack"),
  "/create must expose visible Generate Creative Pack and Cancel controls.",
);
assert.ok(
  createClientSource.includes("withCreativePackTimeout") &&
    createClientSource.includes("CREATIVE_PACK_FORMAT_TIMEOUT_MS") &&
    createClientSource.includes("CREATIVE_PACK_CONCURRENCY") &&
    createClientSource.includes("autoGenerateAudio: false"),
  "Creative Pack must enforce timeout/concurrency and suppress paid auto-audio prewarming.",
);
assert.ok(
  createClientSource.includes("setCreativePackGroups((groups) => groups.map((group) => (") &&
    createClientSource.includes('status: "cancelled"') &&
    createClientSource.includes("Cancelled before it started."),
  "Creative Pack cancel must preserve completed groups and mark pending work cancelled.",
);
assert.ok(
  createClientSource.includes("getDefaultReviewProductHandles") &&
    createClientSource.includes(".filter((product) => product.imageUrl)") &&
    createClientSource.includes("selectedReviewProductHandles"),
  "Creative Pack reviews must resolve selected products, then best sellers, then product images.",
);
assert.ok(
  overviewSource.includes('data-creative-pack-overview="true"') &&
    overviewSource.includes("data-creative-pack-card") &&
    overviewSource.includes("transitionDelay") &&
    overviewSource.includes("grid grid-cols-2"),
  "Creative Pack overview must render all groups in a compact reveal grid.",
);
