import type { StoredWebsiteResearchResult } from "../../features/research/types";

export const makeResearch = (
  overrides: Partial<StoredWebsiteResearchResult> = {},
): StoredWebsiteResearchResult => ({
  sessionId: "session_1",
  researchRunId: "research_1",
  brandSnapshotId: "brand_1",
  websiteUrl: "https://agentenamel.com/",
  finalUrl: "https://agentenamel.com/",
  host: "agentenamel.com",
  brand: {
    name: "Agent Enamel",
    url: "https://agentenamel.com/",
    host: "agentenamel.com",
    title: "Agent Enamel",
    description: "An AI receptionist that answers dental calls and books patients.",
    faviconUrl: null,
    logoUrl: "https://cdn.example/logo.png",
    ogImageUrl: null,
    screenshotUrl: null,
    colors: ["#22C55E", "#0F172A"],
    fonts: { feel: "sans" },
    vibeTags: ["calm"],
  },
  brandBrief: {
    brandName: "Agent Enamel",
    offer: "An AI receptionist that answers dental calls and books patients.",
    audience: "Dental practices missing calls while the front desk is busy.",
    buyerMoments: ["The patient called while the front desk was already juggling check-ins."],
    proof: ["Answers calls and books patients."],
    siteLanguage: ["AI receptionist", "Books patients", "Answers dental calls"],
    ctaDirection: "Book a demo",
    visualNotes: [],
    droppedNoiseSummary: [],
    confidence: "high",
  },
  evidence: {
    headings: ["AI receptionist for dental practices"],
    paragraphs: ["An AI receptionist that answers dental calls and books patients."],
    receipts: {
      specificClaims: ["Answers calls and books patients."],
      buyerMoments: ["The patient called while the front desk was busy."],
      exactSiteLanguage: ["AI receptionist"],
      namedProof: [],
    },
    rawMarkdown: "# Agent Enamel",
  },
  metadata: {},
  branding: {},
  adAngles: [{
    buyer: "dental practice owner",
    moment: "phones pile up during check-ins",
    pain: "new patients hit voicemail",
    proof: "answers calls and books patients",
    sitePhrase: "Books patients",
  }],
  providerStatus: [],
  ...overrides,
});
