import type { TalkingFishNewsProofScene } from "../../scene/types";

export const talkingFishNewsProofScript = [
  "Breaking news.",
  "From Mars, Curiosity just found a sea of tiny honeycomb shapes stretching across an entire valley.",
  "Each polygon is only a few inches wide.",
  "Some may be ancient mud cracks.",
  "Others could have formed when buried water squeezed through the soil.",
  "Scientists are testing the chemistry now.",
  "Mars has officially entered its floor-tile era.",
].join(" ");

export const talkingFishNewsProofScene: TalkingFishNewsProofScene = {
  version: 1,
  format: "talking-fish-news",
  brand: {
    name: "NASA Curiosity",
    url: "https://www.nasa.gov/missions/mars-science-laboratory/curiosity-rover/nasas-curiosity-mars-rover-discovers-field-of-honeycomb-textures/",
    host: "nasa.gov",
    title: "Curiosity discovers Martian honeycomb textures",
    description: "A recent NASA discovery reported by the fixed Talking Fish News anchor.",
    faviconUrl: null,
    logoUrl: null,
    ogImageUrl: null,
    screenshotUrl: null,
    colors: ["#D86C43", "#091D2D"],
    fonts: { feel: "sans" },
    vibeTags: ["news", "science", "mars"],
    receipts: {
      specificClaims: [
        "Curiosity found a field of honeycomb-shaped polygons across Valle Grande.",
        "Individual polygons measure about 1.5 to 3 inches across.",
      ],
      buyerMoments: [],
      exactSiteLanguage: ["This sea of polygons took our breath away."],
      namedProof: ["NASA/JPL-Caltech/MSSS"],
    },
  },
  creative: {
    angleId: "mars-honeycomb-field",
    headline: "Mars has a honeycomb floor.",
    subheadline: "Curiosity found the largest field of Martian polygons seen so far.",
    ctaText: "Read the NASA report",
    headlineType: "receipt_drop",
    selectedPain: "The origin of the polygon field is still unresolved.",
    selectedProof: "NASA published the panorama and close-up images on July 29, 2026.",
  },
  style: {
    backgroundColor: "#06283A",
    textColor: "#F7FFFE",
    accentColor: "#F27B5E",
    fontFeel: "sans",
  },
  audio: {
    status: "generated",
    storageId: "fish-talking-fish-mars-news",
    url: "/talking-fish-news-assets/mars-polygons-narration.wav",
    mimeType: "audio/wav",
    durationMs: 18504,
    durationSeconds: 18.504,
    transcript: talkingFishNewsProofScript,
    captions: [
      { text: "Breaking news.", startMs: 117, endMs: 1075 },
      { text: "From Mars,", startMs: 1222, endMs: 1970 },
      { text: "Curiosity just found a sea", startMs: 2071, endMs: 3626 },
      { text: "of tiny honeycomb shapes", startMs: 3723, endMs: 5010 },
      { text: "stretching across an entire valley.", startMs: 5010, endMs: 6644 },
      { text: "Each polygon is only", startMs: 6908, endMs: 7875 },
      { text: "a few inches wide.", startMs: 7875, endMs: 8953 },
      { text: "Some may be ancient mud cracks.", startMs: 9158, endMs: 10854 },
      { text: "Others could have formed", startMs: 10943, endMs: 12290 },
      { text: "when buried water squeezed through the soil.", startMs: 12290, endMs: 13638 },
      { text: "Scientists are testing the chemistry now.", startMs: 13869, endMs: 15709 },
      { text: "Mars has officially entered its floor-tile era.", startMs: 16169, endMs: 18504 },
    ],
    provider: "fish-studio",
    model: "s2.1-pro-free:105a95c3aa3d4301b175ca1f7b3996ca",
    generatedAt: 1780000000000,
  },
  layout: {
    preset: "talking-fish-news-report",
    durationMs: 18504,
    stationName: "Breaking News",
    anchorOpenImageSrc: "/talking-fish-news-assets/fixed-fish-anchor-open.png",
    anchorClosedImageSrc: "/talking-fish-news-assets/fixed-fish-anchor-closed.png",
    musicBed: {
      src: "/talking-fish-news-assets/bikini-bottom-news-theme.mp3",
      volume: 0.11,
      loop: true,
    },
    speechSegments: [
      { startMs: 117, endMs: 1075 },
      { startMs: 1222, endMs: 1970 },
      { startMs: 2071, endMs: 3626 },
      { startMs: 3723, endMs: 6644 },
      { startMs: 6908, endMs: 8953 },
      { startMs: 9158, endMs: 10854 },
      { startMs: 10943, endMs: 13638 },
      { startMs: 13869, endMs: 15709 },
      { startMs: 16169, endMs: 18504 },
    ],
    linkText: "nasa.gov",
    beats: [
      {
        line: "Breaking news. From Mars, Curiosity just found a sea of tiny honeycomb shapes stretching across an entire valley.",
        proofSrc: "/talking-fish-news-assets/mars-polygons-panorama.jpg",
        startMs: 0,
        endMs: 6100,
      },
      {
        line: "Each polygon is only a few inches wide.",
        proofSrc: "/talking-fish-news-assets/mars-polygons-closeup.png",
        startMs: 6100,
        endMs: 9400,
      },
      {
        line: "Some may be ancient mud cracks. Others could have formed when buried water squeezed through the soil.",
        proofSrc: "/talking-fish-news-assets/mars-polygons-closeup.png",
        startMs: 9400,
        endMs: 14950,
      },
      {
        line: "Scientists are testing the chemistry now. Mars has officially entered its floor-tile era.",
        proofSrc: "/talking-fish-news-assets/mars-miraflores-butte.png",
        startMs: 14950,
        endMs: 18504,
      },
    ],
  },
  metadata: {
    candidateIndex: 0,
    generationBatchId: "talking-fish-news-mars-proof",
    researchRunId: "nasa-curiosity-polygons-2026-07-29",
    brandSnapshotId: "nasa-mars-news-2026-08-04",
    model: "deterministic-proof",
    provider: "deterministic",
    generatedAt: 1780000000000,
  },
};
