import type { TalkingFishNewsProofScene } from "../../scene/types";

export const talkingFishNewsProofScript = [
  "Breaking news. One creative recipe can now make ads for entirely new brands.",
  "A prompt can ask AI for one result, then disappear.",
  "Wiggly keeps rules, examples, and quality checks together so an agent can carry creative judgment into the next brand.",
  "The output is not one ad; it is a repeatable format.",
].join(" ");

export const talkingFishNewsProofScene: TalkingFishNewsProofScene = {
  version: 1,
  format: "talking-fish-news",
  brand: {
    name: "Wiggly",
    url: "https://wiggly.agentenamel.com/",
    host: "wiggly.agentenamel.com",
    title: "Wiggly",
    description: "Creative formats that agents can run again.",
    faviconUrl: null,
    logoUrl: null,
    ogImageUrl: null,
    screenshotUrl: null,
    colors: ["#63E4D2", "#081D35"],
    fonts: { feel: "sans" },
    vibeTags: ["creative", "agentic"],
    receipts: {
      specificClaims: ["Rules, examples, and quality checks travel together."],
      buyerMoments: ["A creative recipe needs to work for the next brand too."],
      exactSiteLanguage: ["Creative formats that agents can run again."],
      namedProof: [],
    },
  },
  creative: {
    angleId: "repeatable-creative-recipe",
    headline: "One recipe. New brands.",
    subheadline: "Wiggly turns creative direction into a repeatable format.",
    ctaText: "Explore Wiggly",
    headlineType: "transformation",
    selectedPain: "A good ad concept disappears after one run.",
    selectedProof: "Rules, examples, and quality checks travel together.",
  },
  style: {
    backgroundColor: "#06283A",
    textColor: "#F7FFFE",
    accentColor: "#63E4D2",
    fontFeel: "sans",
  },
  audio: {
    status: "generated",
    storageId: "local-talking-fish-proof-voice",
    url: "/talking-fish-news-assets/wiggly-report-narration.wav",
    mimeType: "audio/wav",
    durationMs: 18450,
    durationSeconds: 18.45,
    transcript: talkingFishNewsProofScript,
    captions: [
      { text: "One recipe. New brands.", startMs: 0, endMs: 4500 },
      { text: "One ask. Then gone.", startMs: 4500, endMs: 7800 },
      { text: "Rules. Examples. Checks.", startMs: 7800, endMs: 14800 },
      { text: "A format, not a one-off.", startMs: 14800, endMs: 18450 },
    ],
    provider: "upload",
    model: "macos-say-daniel-local-proof",
    generatedAt: 1780000000000,
  },
  layout: {
    preset: "talking-fish-news-report",
    durationMs: 18450,
    stationName: "THE DAILY CURRENT",
    anchorImageSrc: "/talking-fish-news-assets/fixed-fish-anchor.png",
    linkText: "wiggly.agentenamel.com",
    beats: [
      {
        line: "Breaking news. One creative recipe can now make ads for entirely new brands.",
        caption: "ONE RECIPE. NEW BRANDS.",
        proofSrc: "/format-repositories/mugsy-explains-v1/assets/proof/wiggly.png",
        startMs: 0,
        endMs: 4500,
      },
      {
        line: "A prompt can ask AI for one result, then disappear.",
        caption: "ONE ASK. THEN GONE.",
        proofSrc: "/format-repositories/mugsy-explains-v1/assets/proof/prompt.png",
        startMs: 4500,
        endMs: 7800,
      },
      {
        line: "Wiggly keeps rules, examples, and quality checks together so an agent can carry creative judgment into the next brand.",
        caption: "RULES. EXAMPLES. CHECKS.",
        proofSrc: "/format-repositories/mugsy-explains-v1/assets/proof/agent-skill.png",
        startMs: 7800,
        endMs: 14800,
      },
      {
        line: "The output is not one ad; it is a repeatable format.",
        caption: "A FORMAT, NOT A ONE-OFF.",
        proofSrc: "/format-repositories/mugsy-explains-v1/assets/proof/format.png",
        startMs: 14800,
        endMs: 18450,
      },
    ],
  },
  metadata: {
    candidateIndex: 0,
    generationBatchId: "talking-fish-news-wiggly-proof",
    researchRunId: "talking-fish-news-study-2026-08-03",
    brandSnapshotId: "wiggly-proof-2026-08-04",
    model: "deterministic-proof",
    provider: "deterministic",
    generatedAt: 1780000000000,
  },
};
