import type { VisualizerAdScene } from "../features/scene/types";

export const defaultRenderScene: VisualizerAdScene = {
  version: 1,
  format: "visualizer",
  brand: {
    name: "OGTool",
    url: "https://ogtool.com/",
    host: "ogtool.com",
    title: "OGTool",
    description: "Managed Reddit and ChatGPT visibility campaigns.",
    faviconUrl: "https://ogtool.com/favicon.ico",
    logoUrl: null,
    ogImageUrl: null,
    screenshotUrl: null,
    colors: ["#82DFFF"],
    fonts: {
      feel: "sans",
    },
    vibeTags: ["growth"],
    receipts: {
      specificClaims: ["First ChatGPT mention in 14 days."],
      buyerMoments: ["Your competitor shows up in ChatGPT first."],
      exactSiteLanguage: ["ChatGPT mentions in 14 days"],
      namedProof: [],
    },
  },
  creative: {
    angleId: "chatgpt-mentions",
    headline: "Your Competitor Shows Up First",
    subheadline: "First ChatGPT mention in 14 days from managed Reddit and AI visibility campaigns.",
    ctaText: "See the proof",
    headlineType: "contrast",
    selectedPain: "Your competitor shows up in ChatGPT first.",
    selectedProof: "First ChatGPT mention in 14 days.",
  },
  style: {
    backgroundColor: "#FBFAF5",
    textColor: "#070B1D",
    accentColor: "#82DFFF",
    visualizerColor: "#82DFFF",
    visualizer: {
      type: "waveform-strip",
      barCount: 24,
      sensitivity: 1.5,
      heightScale: 0.9,
      baseline: 4,
      gain: 1.7,
      compression: 3,
      floor: 0.08,
      ceiling: 0.86,
      curve: "sqrt",
      bandFocus: "voice",
      mirror: false,
      splitSpeakers: false,
    },
    fontFeel: "sans",
  },
  audio: {
    status: "none",
    transcript: "",
    captions: [],
  },
  layout: {
    preset: "centered-hero",
  },
  metadata: {
    candidateIndex: 0,
    generationBatchId: "render-fixture",
    researchRunId: "research-fixture",
    brandSnapshotId: "brand-fixture",
    model: "fixture",
    provider: "deterministic",
    generatedAt: 123,
    adAngles: [{
      buyer: "D2C founder",
      moment: "a competitor shows up first in a ChatGPT recommendation",
      pain: "buyers trust the answer before they ever visit a site",
      proof: "First ChatGPT mention in 14 days.",
      sitePhrase: "ChatGPT mentions in 14 days",
    }],
  },
};
